ai2sty =
{
    "Style":{
        "Width":{
            "id":"width:",
            "value":"px"
        },
        "Height":{
            "id":"height:",
            "value":"px"
        },
        "TextAlignment":{
            "id":"text-alignment:",
            "value":{
                "0":"left",
                "1":"center",
                "2":"right"
            }
        },
        "BackgroundColor":{
            "id":"background-color:",
            "isColorHex":"true",
            "value":""
        },
        "TextColor":{
            "id":"color:",
            "isColorHex":"true",
            "value":""
        },
        "FontBold":{
            "id":"font-weight:",
            "value":{
                "True":"600",
                "False":"400",
            }
        },        
        "FontSize":{
            "id":"font-size:",
            "value":"px"
        },
        "FontTypeface":{
            "id":"font-family:",
            "value":{
                "":"auto",
                "1":"sans-serif",
                "2":"serif",
                "3":"monospace",
            }
        },         
        "Shape":{
            "id":"border-radius:",
            "value":{
                "":"4px",
                "1":"6px",
                "2":"0px",
                "3":"40px",
            }
        }
    }
}
